name: rl_env
channels:
  - conda-forge
  - pytorch
dependencies:
  - ipykernel
  - ipython
  - numpy
  - matplotlib
  - pandas
  - pip
  - pytorch
  - torchvision
  - tqdm
  - yfinance=0.2.54
  - pip:
      - notebook
      - gym
      - stable-baselines3
      - shimmy
      - rich
      - alpha_vantage